window.env = {
  "TERM_PROGRAM": "vscode",
  "NODE": "/usr/local/bin/node",
  "INIT_CWD": "/Users/moinuddinmasud/Dev/reactjs/spms-sales",
  "TERM": "xterm-256color",
  "SHELL": "/bin/zsh",
  "MAKEFLAGS": "",
  "npm_config_metrics_registry": "https://registry.npmjs.org/",
  "TMPDIR": "/var/folders/h6/qdcvmf_528zfgcjf4lnt59fc0000gn/T/",
  "CPPFLAGS": "-I/usr/local/opt/openjdk@19/include",
  "npm_config_global_prefix": "/usr/local",
  "TERM_PROGRAM_VERSION": "1.80.2",
  "MallocNanoZone": "0",
  "ORIGINAL_XDG_CURRENT_DESKTOP": "undefined",
  "ZDOTDIR": "/Users/moinuddinmasud",
  "COLOR": "1",
  "npm_config_noproxy": "",
  "npm_config_local_prefix": "/Users/moinuddinmasud/Dev/reactjs/spms-sales",
  "ZSH": "/Users/moinuddinmasud/.oh-my-zsh",
  "USER": "moinuddinmasud",
  "LS_COLORS": "di=1;36:ln=35:so=32:pi=33:ex=31:bd=34;46:cd=34;43:su=30;41:sg=30;46:tw=30;42:ow=30;43",
  "COMMAND_MODE": "unix2003",
  "npm_config_globalconfig": "/usr/local/etc/npmrc",
  "SSH_AUTH_SOCK": "/private/tmp/com.apple.launchd.OI1KHywoWY/Listeners",
  "__CF_USER_TEXT_ENCODING": "0x1F5:0:2",
  "npm_execpath": "/usr/local/lib/node_modules/npm/bin/npm-cli.js",
  "MAKELEVEL": "1",
  "PAGER": "less",
  "MFLAGS": "",
  "LSCOLORS": "Gxfxcxdxbxegedabagacad",
  "PATH": "/Users/moinuddinmasud/Dev/reactjs/spms-sales/node_modules/.bin:/Users/moinuddinmasud/Dev/reactjs/node_modules/.bin:/Users/moinuddinmasud/Dev/node_modules/.bin:/Users/moinuddinmasud/node_modules/.bin:/Users/node_modules/.bin:/node_modules/.bin:/usr/local/lib/node_modules/npm/node_modules/@npmcli/run-script/lib/node-gyp-bin:/usr/local/opt/openjdk@19/bin:/Users/moinuddinmasud/go/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/go/bin:/usr/local/share/dotnet:~/.dotnet/tools:/Library/Apple/usr/bin:/Users/moinuddinmasud/.cargo/bin",
  "npm_package_json": "/Users/moinuddinmasud/Dev/reactjs/spms-sales/package.json",
  "_": "/Users/moinuddinmasud/Dev/reactjs/spms-sales/node_modules/.bin/react-dotenv",
  "npm_config_userconfig": "/Users/moinuddinmasud/.npmrc",
  "npm_config_init_module": "/Users/moinuddinmasud/.npm-init.js",
  "USER_ZDOTDIR": "/Users/moinuddinmasud",
  "__CFBundleIdentifier": "com.microsoft.VSCode",
  "npm_command": "run-script",
  "PWD": "/Users/moinuddinmasud/Dev/reactjs/spms-sales",
  "npm_lifecycle_event": "build",
  "EDITOR": "vi",
  "npm_package_name": "spms-app",
  "LANG": "en_US.UTF-8",
  "npm_config_npm_version": "9.8.0",
  "VSCODE_GIT_ASKPASS_EXTRA_ARGS": "--ms-enable-electron-run-as-node",
  "XPC_FLAGS": "0x0",
  "npm_config_node_gyp": "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js",
  "npm_package_version": "0.1.0",
  "XPC_SERVICE_NAME": "0",
  "VSCODE_INJECTION": "1",
  "SHLVL": "2",
  "HOME": "/Users/moinuddinmasud",
  "VSCODE_GIT_ASKPASS_MAIN": "/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/git/dist/askpass-main.js",
  "npm_config_cache": "/Users/moinuddinmasud/.npm",
  "LESS": "-R",
  "LOGNAME": "moinuddinmasud",
  "npm_lifecycle_script": "react-dotenv && craco build",
  "VSCODE_GIT_IPC_HANDLE": "/var/folders/h6/qdcvmf_528zfgcjf4lnt59fc0000gn/T/vscode-git-6b916900b0.sock",
  "GOPATH": "/Users/moinuddinmasud/go",
  "npm_config_user_agent": "npm/9.8.0 node/v18.12.0 darwin x64 workspaces/false",
  "GIT_ASKPASS": "/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/git/dist/askpass.sh",
  "VSCODE_GIT_ASKPASS_NODE": "/Applications/Visual Studio Code.app/Contents/Frameworks/Code Helper (Plugin).app/Contents/MacOS/Code Helper (Plugin)",
  "npm_node_execpath": "/usr/local/bin/node",
  "npm_config_prefix": "/usr/local",
  "COLORTERM": "truecolor",
  "PUBLIC_URL": "/",
  "AUTH_API_URL": "http://35.90.185.130/auth/test",
  "APP_API_URL": "http://35.90.185.130/api/test"
};